/// Flutter icons Queued
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Queued
///      fonts:
///       - asset: fonts/Queued.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Queued {
  Queued._();

  static const _kFontFam = 'Queued';
  static const String _kFontPkg = null;

  static const IconData music_player_fill =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person_lines_fill =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
